### ISSUE TITLE
Word suggestion: Sane

### ISSUE THREAD

**Issue by rickhanlonii** [tatianamac/selfdefined#104]
## Overview

It's common for people to use "sane" as a ableist slur as in "this is a sane pull request" or "our tests provide a sanity check". These usages imply that being sane is good and being neurodiverse is bad or a failure.

Submitting this issue first to get agreement and to discuss how to categorize it before I submit a PR. If this is a good addition, would we add it as it's own page or roll into https://www.selfdefined.app/definitions/crazy/?

**Comment by tatianamac** [comment]
Yes! Absolutely. I've been seeing this usage pop up more and more; even integrated into many tools! 

I would create it as its own word. When we open up/create interlinking, we would then link it to `insane`, `crazy`, etc.

I'm working on reorganising our [documentation](https://www.selfdefined.app/documentation/), so hopefully it makes sense if you decide to open a PR.

Happy to support with editing/ideas if so.
