### ISSUE TITLE
Hompage header text cut off on mobile

### ISSUE THREAD

**Issue by zackkrida** [tatianamac/selfdefined#124]
Hi! On my phone the intro paragraph / subheading of the site gets cut off. 

![screenshot_20200510-190555_chrome](https://user-images.githubusercontent.com/6351754/81512878-32307980-92f2-11ea-89df-aaed3c6063ca.jpg)

I'm happy to submit a pr if desired—thank you for doing this work.

**Comment by tatianamac** [comment]
Hi @zackkrida ! Thanks for filing this issue! I'd love if you could submit a PR!

**Comment by HarshKapadia2** [comment]
@tatianamac I fixed this issue locally by making an addition to `./dist/assets/css/base.css`, but whenever I run `npm run build`, the changes vanish for some reason and Git does not record any changes that I made. When I run `npm run serve` again, the code is back to its original state, ie, without my changes in `base.css`. Could you please tell me what I am doing wrong?

**Comment by ovlb** [comment]
@HarshKapadia2 `./dist` is the build folder, which gets overwritten every time you run a build. The source files are located in [./assets/css/](https://github.com/tatianamac/selfdefined/tree/master/assets/css). You’ll probably find the correct file there. 

If you want to inspect your changes locally you can use `npm run serve`. :)

**Comment by HarshKapadia2** [comment]
Thank you for the reply @ovlb!
I'll make a PR soon!

**Comment by zackkrida** [comment]
@HarshKapadia2 thank you for handling that; looks great!

**Comment by HarshKapadia2** [comment]
No problem and thank you @zackkrida!

**Comment by tatianamac** [comment]
Thank you for filing the issue, @zackkrida  and for jumping on it, @HarshKapadia2 ! I appreciate you both!

Closing this issue manually since I don't think GH allows backwards PR-issue linking 🙃
