### ISSUE TITLE
Incomplete sentence in pronouns definition

### ISSUE THREAD

**Issue by yefim** [tatianamac/selfdefined#130]
Thanks for writing up a definition for pronouns! I noticed what I think is an unfinished sentence under the [Considerations](https://github.com/tatianamac/selfdefined/blob/56b7b074c769e9905c76cfdde1781372681dbcfc/11ty/definitions/pronouns.md#considerations) subheading. I'm quoting the sentence below:

```
Hence, why it is important to
```

I would really appreciate it if the sentence were finished :)

**Comment by tatianamac** [comment]
Thank you! I fixed it but forgot to link the PR.

**Comment by yefim** [comment]
Thanks!
