### ISSUE TITLE
Suggestion: Hawaiian shirts

### ISSUE THREAD

**Issue by ericwbailey** [tatianamac/selfdefined#195]
I'm suggesting the term to give awareness of the symbology utilized by [the accelerationist Boogaloo movement](https://en.m.wikipedia.org/wiki/Boogaloo_movement). In addition, I think there's an opportunity to highlight the cultural appropriation and Colonial history that existed before the movement began.

My question is if this should be defined under the term _boogaloo_—the shorthand reference to _Breakin' 2: Electric Boogaloo_—from which the movement derives its name, or via the Hawaiian shirt? The shirt is not a term, but is a popular article of clothing that many people own and may be unfamiliar with either of its issues. In terms of the project's scope, I view it similar to the [ok-hand](https://www.selfdefined.app/definitions/ok-hand/).

I'm happy to submit a PR for either term if the project feels it is inline with an acceptable contribution.

**Comment by tatianamac** [comment]
Hi @ericwbailey ! There is an existing PR (which is closed bc I had to migrate the app to its own org and rename the main repo) for Boogaloo (#186 ).

I think if you wanted to read over that, it would be most fitting there. Perhaps you could add it as its own note to be a bit more explicit.

**Comment by ericwbailey** [comment]
Oh shoot, sorry I missed that. Will do!

**Comment by kathryngraysonnanz** [comment]
@ericwbailey hey there! jumping in to this because I started the PR with the Boogaloo definition. As @tatianamac noted, I have not re-opened the PR since the migration (life has been hectic – it's on my to-do list for this weekend). If you'd like to connect and work on the definition / PR together, I'd be super open to that :) I think the inclusion of the Hawaiian shirt connection is a good one

**Comment by tatianamac** [comment]
Perfect, thanks, @kathryngraysonnanz ! Closing this issue and redirecting work to the soon-to-be-reopened #186 .

**Comment by ericwbailey** [comment]
@kathryngraysonnanz I would love to collaborate, and I totally get you about hectic page. I set just up a blank Google doc if you're interested in working out of it. My email is `eric.w.bailey@gmail.com` if you want to send me an email address for a collaboration invite.

**Comment by tatianamac** [comment]
@ericwbailey Also if helpful, Kathryn and I are both on our [Slack community](https://join.slack.com/t/selfdefined/shared_invite/zt-en1u6xn8-CumcehUfprC0GH5lamb1bg).

I know it's another Slack community but it's fairly quiet and I find it helpful personally. Up to you.

**Comment by ericwbailey** [comment]
I am running out of sidebar here (joining).
