### ISSUE TITLE
🧹 Consolidate/finalise linting; consider axe Linting and Linkinator

### ISSUE THREAD

**Issue by tatianamac** [tatianamac/selfdefined#202]
##  Overview
Deque just released [axe linter](https://github.com/marketplace/axe-linter). 
I have done no preliminary research on this, but thought it may be helpful to consider for our set up.

To be explicit, I never see linter tools or automated tests  as a replacement for manual user testing in accessibility. Instead, I see them as helpers.

I wanted to bring this up in the context of the other open PRs and issues revolving around our linting set up (I can't tell which of these are open/closed, but probably helpful for context:

- #139 
- #85 
- #74 
- #88 

## Needs
Ideally I'd like to:
- [ ] Decide whether or not we will use axe Linter
- [ ] Decide whether or not we use a link linter (like [Linkinator](http://npm.im/linkinator))
- [ ] Address and close any open PRs/issues around tests/linting
- [ ] Include notes in our documentation

I think this task is probably best suited for someone with someone who has some familiarity with our database, though it is not necessary. Experience in this sort of area for set up would be great.

cc: @greatislander @ovlb for thoughts!

**Comment by greatislander** [comment]
Hi @tatianamac! I agree it would be good to try the new axe-linter. I didn’t get anywhere with running axe-cli in GitHub Actions although I’m sure it is possible.

**Comment by bnb** [comment]
The axe Linter GitHub Action looks pretty nice. As you mentioned, not a replacement but it's a nice gate to have for shipping.

**Comment by ovlb** [comment]
Agreed with axe linter. @bnb, @greatislander Does one of you feel comfortable setting this up?

Linkinator looks interesting. We should give it a try!

**Comment by bnb** [comment]
axe Linter would need to be set up by a repo owner since it's a GitHub app. Should be just a few clicks, though!

**Comment by tatianamac** [comment]
Oh, it's a moot point as it's only free for __personal__ open source projects, not OSS that are on organisation accounts. 😅😭

**Comment by greatislander** [comment]
Dang.

**Comment by wuz** [comment]
@tatianamac I'd like to tackle adding some accessibility linting to the project with Github actions (I'm planning to do a stream tomorrow over this). Is that something you still are interested in, even though axe linter won't work?

**Comment by tatianamac** [comment]
@wuz Yes! I'd love that! Especially if it helps us to streamline/close this linting issue and reincorporate it back into our documentation. ✨ I'm going to assign this to you and mark it as in-progress (we can take it off if you change your mind).

**Comment by wuz** [comment]
Awesome thanks!
