### ISSUE TITLE
✍️ Define master/slave terminology

### ISSUE THREAD

**Issue by tatianamac** [tatianamac/selfdefined#206]
Share context for why this terminology is problematic and share examples of institutions that have fixed it in their architecture.

Provide alternatives.
Provide argumentation for institutions.

Basically, I want this to be a resource for technologists to use to sell in to their bosses (who might be racist and not care), but to get the change instituted in spite of this.

**Comment by bnb** [comment]
Huge +1. This just came up in a discussion I was having and would love to point them to selfdefined ❤️

**Comment by amorriscode** [comment]
Nice to see that [GitHub is working on this](https://twitter.com/natfriedman/status/1271253144442253312).

**Comment by tatianamac** [comment]
@amorriscode For sure. It's helpful when we can make systemic change. Hopefully the addition of the definition will help to provide context for folks.
