### ISSUE TITLE
Word Addition: Fatphobia

### ISSUE THREAD

**Issue by monika** [tatianamac/selfdefined#23]
There are several words and concepts that can be added to this project that are centered around fatphobia. They include (but aren't limited to):

- Fatphobia
- Fat shaming
- Overweight
- Obese

**Comment by tatianamac** [comment]
Absolutely—thank you for suggesting these! 

Are you able to add these as a pull requests? If you're not able, I'm happy to manually add them too once I close out the other pull requests.

**Comment by monika** [comment]
I can add these for sure! If I'm not able to tonight, I can get a PR up tomorrow.

**Comment by flitterbit** [comment]
@monika love this idea. but please remove the "victory hand" emoji from you're profile as it's a transphobic symbol: https://twitter.com/liatrisbian/status/1191729565539938304

**Comment by monika** [comment]
Thanks for the heads up!
