### ISSUE TITLE
Define nerd

### ISSUE THREAD

**Issue by ewuska** [tatianamac/selfdefined#239]
Submitting for consideration the following term and definition draft from the [DDH](https://medium.com/dictionary-of-digital-humanities):

**Nerd**
An overly intellectual person, usually obsessive or lacking social skills, focusing their interests on non-mainstream activities, generally highly technical or related to fiction or fantasy narratives. It is used as a stereotype for either derogatory or praising purposes, depending on who's wielding it.

**Comment by arielsilvestri** [comment]
Hello y'all! I intend to give this definition a submission in the coming days
