### ISSUE TITLE
Define monoculture

### ISSUE THREAD

**Issue by ewuska** [tatianamac/selfdefined#242]
Submitting for consideration the following term and definition draft from the [DDH](https://medium.com/dictionary-of-digital-humanities):

**Monoculture**
State of culture in which there is a relevant lack of diversity in cultural objects produced, both by organizations and audiences.

**Comment by tatianamac** [comment]
I think this is a good candidate for defining!

**Comment by eveline-xie** [comment]
Hi Tatiana, this is my first time contributing! I would like to add the above definition to the app.
