### ISSUE TITLE
Ableist language file is misspelled as 'ablelist-language.md'

### ISSUE THREAD

**Issue by CanadaHonk** [tatianamac/selfdefined#244]
(able**l**ist, shouldn't have an l? Not 100% sure but probably a mistake.)

**Comment by ovlb** [comment]
@Oj18 That’s quite true. Do you feel comfortable opening a pull request to adress this issue? No worries, if not :)

**Comment by CanadaHonk** [comment]
Sure, I can make one later today (but have work for a couple hours so it'll be in a while).

**Comment by ovlb** [comment]
That’s totally fine, these bugs don’t run away :)

**Comment by ovlb** [comment]
I’ll assign this issue to you, so that folx know it’s taken.

**Comment by CanadaHonk** [comment]
Sorry was busy, doing now.

**Comment by CanadaHonk** [comment]
Also, @ovlb for some other issues like misspelling and also adding new definitions should a new issue be opened, then a pull request or can it be just a pull request? Thanks.

**Comment by CanadaHonk** [comment]
(Because in "white feminism" ableist is also spelt "ablelist" - should I make a new issue then PR or just do a PR?)

**Comment by ovlb** [comment]
@Oj18 I second the answer of Tatiana in your PR :)
