### ISSUE TITLE
Revise spelling of antisemitism.

### ISSUE THREAD

**Issue by ellenmacpherson** [tatianamac/selfdefined#275]
At the moment it looks like the term antisemitism is rendered as two words separated by a hyphen (anti-Semitism). Proposing that we revise it to be unhyphenated (antisemitism).

There's considerable concern around the hyphenated spelling as it "allows for the possibility of something called ‘Semitism’, which not only legitimizes a form of pseudo-scientific racial classification that was thoroughly discredited by association with Nazi ideology, but also divides the term, stripping it from its meaning of opposition and hatred toward Jews." 

For further info, see this 2015 [memo](https://www.holocaustremembrance.com/sites/default/files/memo-on-spelling-of-antisemitism_final-1.pdf) from the International Holocaust Remembrance Alliance. 

Discussion very welcome on this, particularly from any Jewish contributors.

**Comment by tatianamac** [comment]
Thank you for opening this issue, @ellenmacpherson ! I've shared it with our Slack community and asked for Jewish folks to provide insights in particular.
