### ISSUE TITLE
Typo in dude entry

### ISSUE THREAD

**Issue by amaralynch** [tatianamac/selfdefined#277]
While our intent may be to make people feel at east or comfortable

Should be “at ease or comfortable”

**Comment by tatianamac** [comment]
@amaralynch Thanks for submitting! Do you feel comfortable submitting a PR for this?

**Comment by amaralynch** [comment]
Sorry.  I'm not familiar with how github works.  What's a PR?

**Comment by tatianamac** [comment]
No sorries! If you'd like to submit what's called a "pull request" (or PR), it requires knowing a little bit of code—we're here to help!

If this isn't something you're interested in, no worries at all, we can have someone else fix it! Mostly I wanted to give you the option without pressure! ✨ Either way we appreciate you submitting the issue!

**Comment by amaralynch** [comment]
Sure!  Always game to learn something new :)

**Comment by tatianamac** [comment]
Awesome! Our [contributing guidelines](https://github.com/selfdefined/web-app/blob/prod/CONTRIBUTING.md) should hopefully give you a place to start!

Also, we have a [Slack community](https://join.slack.com/t/selfdefined/shared_invite/zt-fczgm8b6-8ZZgHvLutNDXo~NjwaL7Iw) that you can join if you'd like to pair program with someone or get support!

**Comment by amaralynch** [comment]
Thanks, Tatiana--Just took a look at the contributing guidelines and I'm
afraid it's more learning than I have capacity to take on in the moment!
Sorry to back out!  Hope to be able to circle back to it at some point.

Best,
Amara

**Comment by ex-shomveerkherwa** [comment]
Hi @tatianamac 
I would like to to make the change and submit a PR, where do I begin?
Thanks
