### ISSUE TITLE
🚩 Include flag context in excerpt

### ISSUE THREAD

**Issue by tatianamac** [tatianamac/selfdefined#280]
## Current Behaviour
The excerpt, which is used for social media and search engine previews, currently automatically prepends the word "avoid" if a term should be avoided and has an "avoid" flag in its definition.

## Desired Behaviour
The excerpt could also append the circumstances, such as "avoid: racist term."

## Notes
- See #262 for further details.

**Comment by yourpalkat** [comment]
I can take this one on, if no one minds! Nice way to ease into remembering where everything lives in 11ty.

**Comment by ovlb** [comment]
@derekmurr Go for it :)

**Comment by tatianamac** [comment]
Thank you, @derekmurr ! Let us know if we can support in any way.
