### ISSUE TITLE
The flag in "psychopath" has a type value and it should be text instead.

### ISSUE THREAD

**Issue by mjoynes-wombat-web** [tatianamac/selfdefined#286]
The psychopath definition has a flag which has a type. This key should be text instead.

https://github.com/selfdefined/web-app/blob/prod/11ty/definitions/psychopath.md

**Comment by mjoynes-wombat-web** [comment]
I will claim and fix this.

**Comment by tatianamac** [comment]
Thank you, @ssmith-wombatweb !

**Comment by mjoynes-wombat-web** [comment]
Do I close the issue before or after the pull request is accepted?
