### ISSUE TITLE
Add attribution to excerpt in ableism definition

### ISSUE THREAD

**Issue by oakthielbar** [tatianamac/selfdefined#289]
The first line of the body of the definition of ableism is followed by an attribution, but there is no attribution in the excerpt. Given that the excerpt is displayed in isolation, it is effectively claiming the original words of another author.

I believe that this specific situation needs to be addressed with some urgency since this excerpt is currently visible in search results, and to that end, I have made a branch and will soon open a PR to address it.

**Comment by tatianamac** [comment]
In 100 percent agreement, in particular because it could be read as erasure of a Black woman's words, which I do not want to do!
