### ISSUE TITLE
Excerpt for "barbaric" missing context on harm

### ISSUE THREAD

**Issue by oakthielbar** [tatianamac/selfdefined#290]
I noticed when reviewing the current excerpts that they reproduce the first line of the definition. Is that the intended format for excerpts? Some of the definitions lead with a line that explains the purely grammatical and linguistic function of a term without any context, and I worry that a direct copy of just the first line could perpetuate the harmful use of some terms.

The current excerpt for "barbaric" is an example where the context of harm is missing. I believe that it should be updated to reflect the values and goals of this project.

**Comment by tatianamac** [comment]
@oakthielbar Thanks for opening this PR. It makes sense to me what you're saying. Another note i want to make is that we're working on automagically prepending the warning flags to words where they exist in #280. I think that addresses some concern.

Would you be willing to open a PR to address this word? If so, I'd be happy to co-author/edit with you. 💙

**Comment by tatianamac** [comment]
Did not mean to close! 😅

**Comment by oakthielbar** [comment]
@tatianamac I've opened #293 for addressing this issue.

Prepending warning flags definitely helps to address the concern here. With that in place, it would be clear that an "avoid" flagged word is harmful.

I may be overthinking it, but I think that the excerpts should be highlighting the information that is most pertinent from the definition rather than the sometimes dry and contextless definitions of those words (as with excerpts from established dictionaries such as Merriam-Webster). The risk of focusing on contextless definitions is that someone who is new to English or otherwise refining their understanding might stop at the excerpt and take it at face value.

I'm not trying to indicate that I perceive any disagreement on this, just that I want to clarify my thoughts on this.

**Comment by tatianamac** [comment]
Perfect. I will look at the PR!

We're in agreement about this approach; in reviewing I think I was excited to get the issues fixed and in retrospect should have read more critically. I appreciate your careful thought around this so we can address. I didn't read it as disagreement AND I appreciate your clear communication around it either way!
