### ISSUE TITLE
Docs: Improve Contribution Guides

### ISSUE THREAD

**Issue by ovlb** [tatianamac/selfdefined#32]
With the merge of #31 we have some basic documentation on the website and in `contributing.md`. However, this needs to be fleshed out. The following points would need to be addressed:

- [ ] Preferred way of proposing/updating definitions is through issues.
- [ ] Add more examples to website docs
- [ ] Create issue templates ([docs here](https://help.github.com/en/github/building-a-strong-community/configuring-issue-templates-for-your-repository)) to help structuring contributions

**Comment by laurakalbag** [comment]
I’d love to request (I’d be happy to do this once I’ve managed to get it working for myself!)

- [ ] Quickstart guide for people setting up the dev environment for themselves.

**Comment by ovlb** [comment]
@laurakalbag 

That’s a very good point! Where are you stuck? Have you seen this (very rudimentary) page? https://www.selfdefined.app/documentation/development/

**Comment by laurakalbag** [comment]
@ovlb thank you! Sorry, I’d completely missed this page. I think it’s a great start, for one because it completely answers why I was getting wonky output (I was running the default 11ty command.)

Maybe we should add a link to this guide under a ‘Development’ heading on the readme?

**Comment by tatianamac** [comment]
@laurakalbag I think that'd be a really helpful addition. What do you think @ovlb ?

**Comment by outoftardis** [comment]
It's about README, but I think it's related to this issue as it's also about contributing:

- [ ] The link to the code of conduct in README does not work
- [ ] I agree with @laurakalbag that you need a link to your documentation from README, but I'd suggest you add the most useful links right under the title. It could look something like: Documentation | Contributing Guide | .... 

I can work on this when I'm done with PR #54

**Comment by tatianamac** [comment]
Thank you, @outoftardis! As it was already accessible to me, I went ahead and made your suggested updates to the README.
