### ISSUE TITLE
Add fatmisia (and other "-misia" alternatives?) as an addition/alternative to fatphobia

### ISSUE THREAD

**Issue by shimmoril** [tatianamac/selfdefined#35]
This [article from the Simmons University Library](https://simmons.libguides.com/anti-oppression#s-lib-ctab-10174165-1) is a great introduction to the differences and distinctions between the "-phobia" and "-misia" suffixes. 

As noted in the Simmons article, the use of "-phobia" equates bigotry with mental health issues, and similar to other definitions in Self-Defined, it can also leave room for bad-faith arguments about how someone isn't "afraid" of x, they just don't like/believe in it etc. 

There are a number of fat liberation activists writing about fatmisia, including [Kivan Bay](https://twitter.com/kivanbay) who also writes about the [intersection of fatmisia and transmisia](https://medium.com/@kivabay/the-intersection-of-fatmisia-and-transmisia-78fb10f90551).

**Comment by tatianamac** [comment]
@shimmoril (I accidentally never wrote you back on this!) Thank you so much for sharing this! Would you have interest in submitting a PR with a definition for this? 

No worries if not, but wanted to ask!

**Comment by shimmoril** [comment]
Any other time I’d love to, but I’m afraid I just don’t have the spoons right now. Appreciate you checking in with me, and I’ll keep an eye on Self-Defined for other opportunities to contribute. 

Ashleigh Lodge

**Comment by tatianamac** [comment]
@shimmoril I opened a PR to define misia. If you have time/energy/desire, I'd love your thoughts on it. Absolutely understand if you're not able! 💙🙏🏽

**Comment by shimmoril** [comment]
I probably did not do that at all correctly, but I’ve added some comments to the PR. It’s a really solid definition, thank you!
