### ISSUE TITLE
Define "weaponize"

### ISSUE THREAD

**Issue by terrifricker** [tatianamac/selfdefined#356]
Resources:
https://slate.com/human-interest/2016/08/how-weaponize-became-a-political-cultural-and-internet-term-du-jour.html
https://www.macmillandictionary.com/us/dictionary/american/weaponize
https://dictionary.cambridge.org/us/dictionary/english/weaponize

**Comment by tkshill** [comment]
May I try this one?

**Comment by tatianamac** [comment]
@tkshill I'd love that! Someone started a [PR](https://github.com/selfdefined/web-app/pull/358), so perhaps you could provide feedback with the definition/resources here?

(Sorry the auto-linking didn't work!)

**Comment by tkshill** [comment]
I can do that

**Comment by tkshill** [comment]
@tatianamac Added a comment to issue #358 providing a definition for `weaponize`. Not sure if I did it exactly right, but I tried to follow some of the examples in the contributing docs.

**Comment by tatianamac** [comment]
@tkshill You did perfectly!!! 🎉
