### ISSUE TITLE
Define "dumbfounded" & "dumbstruck"

### ISSUE THREAD

**Issue by Primigenus** [tatianamac/selfdefined#365]
Both of these build on the ableism inherent in "[dumb](https://www.selfdefined.app/definitions/dumb/)"
We could make these definitions children of that word.

Some alternatives:
astounded
awestruck
flabbergasted
nonplussed

Some quick research:
https://cishits.tumblr.com/post/79281810833/two-things-1-i-feel-like-ableist-language-is
https://www.quora.com/Do-you-know-when-you-are-using-derogatory-ableist-language/answer/Jayden-Brunner

**Comment by tatianamac** [comment]
Thank you for submitting, @Primigenus ! One way we've handled this in the past is to create a "Related words" section, then broke down the "alternatives" section into noun/adjective, etc. Would you have capacity/be willing to open a PR for this sort of change? I would be happy to support.

**Comment by tatianamac** [comment]
@Primigenus : Would you be available to review my PR #435 ?
