### ISSUE TITLE
Slack community invitation link on contributing guidelines page has expired

### ISSUE THREAD

**Issue by jtheory** [tatianamac/selfdefined#382]
Clicking the link to join the [Slack community](https://github.com/selfdefined/web-app/blob/prod/CONTRIBUTING.md#get-help) leads me to a page that reads "This link is no longer active".

Previous PR: #344

**Comment by mpcsh** [comment]
We've moved to Discord! https://twitter.com/TatianaTMac/status/1386857716463796228?s=20

**Comment by qrazi** [comment]
As far as I can tell PR #344 has been deployed, and the link mentioned in the initial post is updated to point to Discord. I think this issue can be closed now?

**Comment by tatianamac** [comment]
Yes, resolved! Thanks for reporting @jtheory and updating @mpcsh @qrazi !
