### ISSUE TITLE
Define "Semitic"

### ISSUE THREAD

**Issue by kristicunga** [tatianamac/selfdefined#385]
**Adj.**

1. Related to languages, races, and culture of people who live or come from across part of western Asia and northern Africa. There are included Arabic, Hebrew, Aramaic and Amharic.
2. Mainly referred to as Arabic and Hebrew

_Arabic and Hebrew are the most spoken Semitic languages._

Sources:

* [Merriam-Webster Dictionary](https://www.merriam-webster.com/dictionary/Semitic)
* [Oxford Learner's Dictionaries](https://www.oxfordlearnersdictionaries.com/definition/english/semitic)
* [Cambridge Dictionary](https://dictionary.cambridge.org/dictionary/english/semitic)
* [Urban Dictionary](https://www.urbandictionary.com/define.php?term=Semitic)

**Comment by tatianamac** [comment]
Thanks for submitting this, @kristicunga ! Would you be interested in either writing the entry for it or providing feedback as an editor?

**Comment by kristicunga** [comment]
Of course @tatianamac! It would be my pleasure 😀
