### ISSUE TITLE
Ampersand character rendered as raw HTML entity code

### ISSUE THREAD

**Issue by medecau** [tatianamac/selfdefined#392]
On the _antisemitism_ definition page in the "_Further Reading_" section there are some links, one of which has an _ampersand_ character that is being rendered as an HTML entity code instead of the logogram that would be expected in an anchor text.

**Comment by tatianamac** [comment]
Thanks for reporting, @medecau! And thanks for picking this up, @qrazi !

**Comment by tatianamac** [comment]
Fixed by #397 .
