### ISSUE TITLE
🎨 Fix red flag splitting across two lines

### ISSUE THREAD

**Issue by laurakalbag** [tatianamac/selfdefined#41]
<img width="300" alt="Screenshot 2020-01-15 at 14 47 06" src="https://user-images.githubusercontent.com/266663/72443468-36b2ae80-37a6-11ea-866a-f631eb28ea54.png">

Depending on the column flow, flags are occasionally split across two lines of text. More often it happens with longer words and longer flags.

**Comment by michaelspellacy** [comment]
Hi @tatianamac. Busy week. Will swing back round to this tomorrow.
