### ISSUE TITLE
Spongebob case

### ISSUE THREAD

**Issue by FennelAurora** [tatianamac/selfdefined#417]
I'm not seeing a good way to add information about the alternating upper and lower letters, which comes from mocking how certain disabled people speak (before that from "a meme where Spongebob is bent at odd angles and often has that text superimposed in that casing on it" - Tatiana, hence the ticket title).

Ie, is there a good way to make entries for a more general pattern, rather than for a specific word?
I'm assuming this could start with a "spongebob case" entry, just that I'd be surprised if I'm alone in not previously knowing that's what it's called, so probably wouldn't have found it.

**Comment by gorlanova** [comment]
could it be a sub-section of ableism ? we could put "behaviours" or "examples of --x in everyday life" to provide context on what could be defined as "--x" (in that case, ableism) as a section in the main definition page ?

maybe later if we have more of those we could then create a section "problematic behaviours" (this should be broader than just behaviours but we can figure that out in due time) on the home page ?

**Comment by tatianamac** [comment]
@Gorlanova I love that suggestion! I also think that Spongebob case should be its own term (cross-linked, as you suggested) to help spread the word and assign a name to a common use!

@FennelAurora I think we could add "alternating case" or something a bit more descriptive. It's a bit of chicken-egg. If we make the term, people can then start to learn it. But I get your points!

**Comment by tatianamac** [comment]
@FennelAurora @Gorlanova Would love if you both could review my PR #436 !

**Comment by FennelAurora** [comment]
Done from my side, thanks!
