### ISSUE TITLE
Linting: unrelated trailing space issue

### ISSUE THREAD

**Issue by AishaBlake** [tatianamac/selfdefined#423]
I worked on PR #422 to add the word "albino" and running the tests surfaced an issue with a trailing space in the definition for ADD/ADHD:

`[lint:markdown] 11ty/definitions/add-adhd.md:20:751 MD009/no-trailing-spaces Trailing spaces [Expected: 0 or 2; Actual: 1]`

**Comment by tatianamac** [comment]
On it! Thanks for filing the bug!
