### ISSUE TITLE
Link on "Semitic" page is broken

### ISSUE THREAD

**Issue by frogsquire** [tatianamac/selfdefined#447]
The link on this page:

https://www.selfdefined.app/definitions/semitic/

(under "related terms" it is the only link)

which should go to 

https://www.selfdefined.app/definitions/antisemitism/

instead goes to 

https://www.selfdefined.app/definitions/antisemitic

**Comment by ovlb** [comment]
Thanks for bringing this to our attention. 

Pinging @tatianamac on this. I guess it would make sense to change it to the existing antisemitism page as it’s probably unlikely that we’ll have a separate page for antisemitic in the future?

**Comment by tatianamac** [comment]
@frogsquire Thanks for the issue and ping @ovlb ! Opened a fix.

**Comment by frogsquire** [comment]
Thank you! At a future point, it might be good to have a discussion about the contents of the antisemitism page itself; specifically, while the point that Jews are not an Ashkenazi/white monolith is important, the idea of Jews as a "global race" has been co-opted by antisemites and it's important to distinguish the truth from those skewed views.

But that's beyond the scope of this issue, if/when I have time to think on the wording, I will open another ticket.

**Comment by tatianamac** [comment]
> Thank you! At a future point, it might be good to have a discussion about the contents of the antisemitism page itself; specifically, while the point that Jews are not an Ashkenazi/white monolith is important, the idea of Jews as a "global race" has been co-opted by antisemites and it's important to distinguish the truth from those skewed views.
> 
> But that's beyond the scope of this issue, if/when I have time to think on the wording, I will open another ticket.

@frogsquire Thanks for opening this issue. I'll look forward to seeing your new ticket around the globalisation piece! Happy rest of the year. :)
