### ISSUE TITLE
Visual bug when first loading a page in Safari

### ISSUE THREAD

**Issue by alexwlchan** [tatianamac/selfdefined#5]
Safari 12.1.2, macOS 10.14.6. Spotted as of just now.

If I load https://selfdefined.netlify.com/#crazy at a window width of ~1220px, the left-hand column layout leaks into the right-hand column:

<img width="1338" alt="Screenshot 2019-10-19 at 23 12 18" src="https://user-images.githubusercontent.com/301220/67151959-0900bb00-f2c6-11e9-8239-339b02e4f4fa.png">

As soon as I change the width of the window, the content reflows back into the two-column layout:

<img width="1333" alt="Screenshot 2019-10-19 at 23 14 35" src="https://user-images.githubusercontent.com/301220/67151976-4bc29300-f2c6-11e9-9580-fe208d4a6ab8.png">

**Comment by tatianamac** [comment]
Thank you, @alexwlchan ! 

Do you mind checking now to see if [my fix](https://github.com/tatianamac/selfdefined/commit/f2d317de147f81aac760ccfb437e8d3e8b289e97) worked for you?

**Comment by alexwlchan** [comment]
Can't reproduce now, so I reckon this is fixed. Thanks!
