### ISSUE TITLE
Proposed change to definition of polyamory

### ISSUE THREAD

**Issue by alexiswatson** [tatianamac/selfdefined#51]
First, this project is rad.   :>

As someone who has practiced polyamory and other forms of ethical non-monogamy, I'd propose a change to polyamory's definition:

> an umbrella term for various types of relationships where all partners involved consent to non-monogamy, such as ~~open relationships,~~ polycules, throuples, group marriages, etc.

While there are absolutely plenty of ways to practice polyamory, the greater umbrella term I've seen used most often is "ethical non-monogamy." In my experience, one of the stigmas polyamorous people face is that it's perceived as "just about sex," and it is often conflated with open relationships that are otherwise romantically exclusive as a result. What distinguishes polyamory ("many loves," albeit in an awkward union of Greek and Latin) is the conscious choice to cultivate and allow the space for multiple relationships that might be coded as romantic or quasi-romantic, which may or may not involve sex at all.

Would love to hear other thoughts on this.

**Comment by tatianamac** [comment]
@alexiswatson This is a super good point. I have proposed a longer, hopefully more nuanced definition based on your feedback for discussion. 

> an umbrella term for various types of relationships **(coded as romantic or quasi-romantic, sexual or non-sexual)** where all partners involved consent to **ethical** non-monogamy, such as ~open relationships,~ polycules, throuples, group marriages, etc.

Also, before I put it on blast, I was curious if it would be helpful for me to post this on Self-Defined's Twitter (which I would RT from my personal account) to elicit more opinions from folks from the community. 

Of immediate priority for me is to get a code of conduct as we start having very nuanced discussions, we need a framework to protect people having sensitive discussions.

Thank you again!

**Comment by alexiswatson** [comment]
@tatianamac The rework you propose is amazing, thank you!

I think opening this up to broader good-faith discussion is a fantastic idea, though I'm 100% on board with ensuring a code of conduct is in place, first. 

Not sure if you have a direction in mind for the CoC, though if you'd like to link that issue as a blocker here when the time comes, I'd be happy to contribute an extra set of eyes if you like.

**Comment by tatianamac** [comment]
Awesome. Are you able to make a pull request with the proposed changes?

I will in the meantime open an issue for a code of conduct

**Comment by alexiswatson** [comment]
Gladly—feel free to ping if there's anything I can lend a hand with.

**Comment by tatianamac** [comment]
Closed with #80 . Thank you, @alexiswatson !
