### ISSUE TITLE
Build script places output CSS in `assets` folder

### ISSUE THREAD

**Issue by dengeist** [tatianamac/selfdefined#55]
**Reproduction steps:**
1. Clone the `selfdefined` repo.
2. Install its dependencies (`npm install`).
3. Execute `npm run build`

**Expected behavior:**
The CSS, along with the other production files, is compiled into the `dist` directory, where it can be ignored by the developer's version control.
<img width="225" alt="Screen Shot 2020-02-06 at 2 46 32 PM" src="https://user-images.githubusercontent.com/13525251/73985240-8725b380-48ef-11ea-9323-3e0429eb1344.png">

**Actual behavior:**
The CSS appears om `/assets/css`, where version control recognizes and attempts to track it.

**Proposed solution:**
Modify the `build:css` script so that parcel outputs to `/dist/assets/css/`

**Comment by ovlb** [comment]
Yip. 🙈  Thanks for putting this on my radar.  

I will open a PR tomorrow to clean up folder structure and build output asap (also addressing #56).
