### ISSUE TITLE
Proposal: use a custom focus indicator

### ISSUE THREAD

**Issue by dengeist** [tatianamac/selfdefined#59]
## Problem
The default focus indicators provided by some browsers and operating systems are inaccessible to many users. The below screenshot of selfdefined illustrates the default focus indicator in Firefox: a thin, dotted outline.
<img width="215" alt="" src="https://user-images.githubusercontent.com/13525251/74050964-eafdba00-498b-11ea-9a66-be2c61a827ef.png">
## Solution
Use the `:focus` pseudoclass to define a custom color and style for the focus outline in selfdefined. Ensure that the color contrast is at least 3:1 with the background of the app.

The [`$primary-color` defined in `base.css`](https://github.com/tatianamac/selfdefined/blob/master/assets/css/base.scss#L34) would be a great solution here!
## Further reading
- [Understanding Success Criterion 2.4.7: Focus Visible](https://www.w3.org/WAI/WCAG21/Understanding/focus-visible.html)
- [Understanding Success Criterion 1.4.11: Non-text Contrast](https://www.w3.org/WAI/WCAG21/Understanding/non-text-contrast.html)

**Comment by tatianamac** [comment]
Thanks for this, @dengeist ! I'm appending a label of good first issue here as I think it could be a good start for a new front end dev. 💙
