### ISSUE TITLE
Word definition links need focus management

### ISSUE THREAD

**Issue by dengeist** [tatianamac/selfdefined#60]
## Problem
Clicking on a definition scrolls the user to that definition, but:
- Keyboard focus remains on that link, which could confuse keyboard users and especially screen-reader users
- Because multiple definitions appear close together, it is not always obvious where a sighted user's attention should go
## Proposed solution
- Use tabindex and javascript to move focus to the heading where a word is defined
- Apply a gentle, temporary highlight to the wrapper behind the definition, so sighted users know where to look
## Further reading
This codepen on [drawing attention to internal focus](https://codepen.io/dengeist/pen/vYOEXgg) utilizes a pattern that I think would be helpful here.

**Comment by ovlb** [comment]
Thanks for all your refinements, EJ. 

I would propose to solve this issue by implementing #53 to make the pages easier to scan in the first place.

**Comment by dengeist** [comment]
I like the idea of #53! Decluttering the main page could help from a cognitive standpoint as well.
