### ISSUE TITLE
✍️ Add code of conduct

### ISSUE THREAD

**Issue by tatianamac** [tatianamac/selfdefined#68]
Add code of conduct language to site. Eventually I would like to adjust/customise given the uniqueness of this project, but we need something in place immediately given the sensitivity of the discussions we have.

[Contributor Covenant](https://www.contributor-covenant.org/) I think is a good place to start

**Comment by ovlb** [comment]
+1 for Contributor Covenant.

**Comment by tatianamac** [comment]
I updated the [README](https://github.com/tatianamac/selfdefined/blob/master/README.md) and am closing this issue.

**Comment by ovlb** [comment]
@tatianamac I think it is considered best practice to have a full copy of the CoC as `CODE_OF_CONDUCT.md` in the root of the repo. The copy of CoC gives contact information specific to the project.

See as an example Tournant UI (shameless plug): https://github.com/tournantdev/ui/blob/master/CODE_OF_CONDUCT.md

**Comment by tatianamac** [comment]
doh, ofc. I'm such a spacecase. Modified it a bit to include some dictionary-specific language; will revisit in the future for more nuance. Uploaded now! 💙
