### ISSUE TITLE
Definition for how to refer to pronouns

### ISSUE THREAD

**Issue by thomplinds** [tatianamac/selfdefined#86]
Found an instance of `Preferred Pronouns` in my application which I knew was incorrect as it implies gender is merely a preference. Would like a reference in selfdefinedapp that explains how to appropriately discuss pronoun usage.

https://twitter.com/TatianaTMac/status/1230611632352456704?s=20

(fwiw I'm happy to submit the PR for this just feel uneducated on the topic myself, doing more research before I submit)

**Comment by vaibhavvikas** [comment]
Your tweet can't be accessed. It's gonna be better if you make it public.

**Comment by thomplinds** [comment]
With @tatianamac 's permission I can add screenshots from the conversation, she locked her twitter account and I don't want to add them without a go ahead from her.

**Comment by tatianamac** [comment]
You’re welcome to paste the screenshots/live text (for accessibility). 

I had to lock down my account due to harassment, so I won’t be unlocking it for w bit at least.
